import uuid

from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Count, Prefetch, Q, Sum
from django.db.models.functions import Coalesce
from django.shortcuts import get_object_or_404
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView

from .authentication import DeviceTokenAuthentication
from .models import (
    ExerciseSet, Lesson, Progress, Question,
    SchoolClass, Student, Unit, UsageEvent,
)
from .permissions import IsStudent
from .serializers import (
    BossResultSerializer,
    ExerciseSetSerializer,
    JoinClassSerializer,
    LeaderboardEntrySerializer,
    LessonCompleteSerializer,
    LessonSerializer,
    UnitSerializer,
    UnitWithProgressSerializer,
    UsageEventSerializer,
)


class StudentAuthMixin:
    """Applies DeviceTokenAuthentication + IsStudent to any view that inherits it."""
    authentication_classes = [DeviceTokenAuthentication]
    permission_classes     = [IsStudent]


# ── POST /api/classes/join/ ───────────────────────────────────────────────────

class JoinClassView(APIView):
    """
    Public — no auth required.

    Join-code auth flow (ARCHITECTURE.md):
      • Nickname not in class  → create Student, issue device_token.
      • Nickname exists + PIN matches → rotate device_token (new-device re-entry).
      • Nickname exists + PIN wrong  → 401.
    """

    authentication_classes = []
    permission_classes     = []

    def post(self, request):
        ser = JoinClassSerializer(data=request.data)
        ser.is_valid(raise_exception=True)

        join_code = ser.validated_data['join_code'].strip().upper()
        nickname  = ser.validated_data['nickname']   # stripped by serializer validator
        pin       = ser.validated_data['pin']

        school_class = get_object_or_404(
            SchoolClass.objects.select_related('school', 'subject'),
            join_code=join_code,
        )

        try:
            student = Student.objects.get(
                school_class=school_class,
                nickname__iexact=nickname,
            )
        except Student.DoesNotExist:
            student = Student.objects.create(
                school_class=school_class,
                nickname=nickname,
                pin=pin,
                # device_token auto-generated by model default (uuid.uuid4)
            )
        else:
            # Nickname already in this class — gate re-entry on correct PIN
            if student.pin != pin:
                return Response(
                    {'error': 'Incorrect PIN. Ask your teacher if you have forgotten it.'},
                    status=status.HTTP_401_UNAUTHORIZED,
                )
            # Rotate token: old device's cached token is immediately invalidated
            student.device_token = uuid.uuid4()
            student.save(update_fields=['device_token'])

        return Response({
            'device_token': str(student.device_token),
            'student_id':   student.id,
            'nickname':     student.nickname,
            'class_name':   school_class.name,
            'subject_id':   school_class.subject_id,
        })


# ── GET /api/units/ ───────────────────────────────────────────────────────────

class UnitListView(StudentAuthMixin, generics.ListAPIView):
    """
    Units for the student's subject with locked state + boss config.
    One extra query fetches all Progress rows up front so is_locked is
    computed without per-unit DB hits.
    """

    serializer_class = UnitSerializer

    def get_queryset(self):
        return (
            Unit.objects
            .filter(subject=self.request.user.school_class.subject)
            .select_related('boss')
            .order_by('order')
        )

    def get_serializer_context(self):
        ctx = super().get_serializer_context()
        ctx['progress_map'] = {
            p.unit_id: p
            for p in Progress.objects.filter(student=self.request.user)
        }
        return ctx


# ── GET /api/units/<pk>/lessons/ ─────────────────────────────────────────────

class UnitLessonListView(StudentAuthMixin, generics.ListAPIView):
    """Lessons for one unit, ordered. 404 if the unit isn't in the student's subject."""

    serializer_class = LessonSerializer

    def get_queryset(self):
        unit = get_object_or_404(
            Unit,
            pk=self.kwargs['pk'],
            subject=self.request.user.school_class.subject,
        )
        return Lesson.objects.filter(unit=unit).order_by('order')


# ── GET /api/units/<pk>/exercise-sets/ ───────────────────────────────────────

class UnitExerciseSetListView(StudentAuthMixin, generics.ListAPIView):
    """
    Exercise sets with nested questions for one unit.
    The frontend filters questions by template_tag when starting a boss fight.
    """

    serializer_class = ExerciseSetSerializer

    def get_queryset(self):
        unit = get_object_or_404(
            Unit,
            pk=self.kwargs['pk'],
            subject=self.request.user.school_class.subject,
        )
        return (
            ExerciseSet.objects
            .filter(unit=unit)
            .prefetch_related(
                Prefetch(
                    'questions',
                    queryset=Question.objects.order_by('difficulty', 'id'),
                )
            )
        )


# ── POST /api/progress/lesson-complete/ ──────────────────────────────────────

class LessonCompleteView(StudentAuthMixin, APIView):

    def post(self, request):
        ser = LessonCompleteSerializer(data=request.data)
        ser.is_valid(raise_exception=True)

        student = request.user

        if ser.validated_data['student_id'] != student.id:
            return Response(
                {'error': 'student_id does not match authenticated student.'},
                status=status.HTTP_403_FORBIDDEN,
            )

        lesson = get_object_or_404(
            Lesson.objects.select_related('unit'),
            pk=ser.validated_data['lesson_id'],
        )

        if lesson.unit.subject_id != student.school_class.subject_id:
            return Response(
                {'error': 'Lesson does not belong to your subject.'},
                status=status.HTTP_403_FORBIDDEN,
            )

        progress, _ = Progress.objects.get_or_create(
            student=student,
            unit=lesson.unit,
        )
        progress.lessons_completed.add(lesson)

        completed_ids = sorted(
            progress.lessons_completed.values_list('id', flat=True)
        )
        total_lessons = Lesson.objects.filter(unit=lesson.unit).count()

        return Response({
            'lesson_id':               lesson.id,
            'unit_id':                 lesson.unit_id,
            'lessons_completed':       completed_ids,
            'lessons_completed_count': len(completed_ids),
            'total_lessons':           total_lessons,
            'all_lessons_done':        len(completed_ids) >= total_lessons,
        })


# ── POST /api/progress/boss-result/ ──────────────────────────────────────────

class BossResultView(StudentAuthMixin, APIView):

    def post(self, request):
        ser = BossResultSerializer(data=request.data)
        ser.is_valid(raise_exception=True)

        student = request.user
        data    = ser.validated_data

        if data['student_id'] != student.id:
            return Response(
                {'error': 'student_id does not match authenticated student.'},
                status=status.HTTP_403_FORBIDDEN,
            )

        unit = get_object_or_404(
            Unit.objects.select_related('boss'),
            pk=data['unit_id'],
            subject=student.school_class.subject,
        )

        progress, _ = Progress.objects.get_or_create(student=student, unit=unit)

        progress.total_xp += data['xp']

        if data['won']:
            progress.boss_defeated = True
            # Golden = no hearts lost (hearts_left equals the boss's starting hearts)
            try:
                if data['hearts_left'] >= unit.boss.hearts:
                    progress.golden_boss_defeated = True
            except ObjectDoesNotExist:
                pass

        progress.save(update_fields=['total_xp', 'boss_defeated', 'golden_boss_defeated'])

        return Response({
            'unit_id':              unit.id,
            'boss_defeated':        progress.boss_defeated,
            'golden_boss_defeated': progress.golden_boss_defeated,
            'total_xp':             progress.total_xp,
        })


# ── GET /api/progress/<student_id>/ ──────────────────────────────────────────

class StudentProgressView(StudentAuthMixin, APIView):
    """
    Full progress snapshot — used to resume on any device.
    Returns all units (with locked state + per-unit progress) in one response.
    Total DB queries: 4 (units, progress, prefetch M2M, lesson counts).
    """

    def get(self, request, student_id):
        student = request.user

        if student.id != student_id:
            return Response(
                {'error': 'You may only view your own progress.'},
                status=status.HTTP_403_FORBIDDEN,
            )

        subject = student.school_class.subject

        units = (
            Unit.objects
            .filter(subject=subject)
            .select_related('boss')
            .order_by('order')
        )

        # Fetch all progress rows with lessons_completed prefetched
        # so the serializer can call .all() without per-unit DB hits.
        progress_qs = Progress.objects.filter(student=student).prefetch_related(
            Prefetch('lessons_completed', queryset=Lesson.objects.only('id'))
        )
        progress_map = {p.unit_id: p for p in progress_qs}

        # Total lesson count per unit — single aggregation query
        lesson_count_map = dict(
            Lesson.objects
            .filter(unit__subject=subject)
            .values('unit_id')
            .annotate(n=Count('id'))
            .values_list('unit_id', 'n')
        )

        unit_data = UnitWithProgressSerializer(
            units,
            many=True,
            context={
                'progress_map':     progress_map,
                'lesson_count_map': lesson_count_map,
            },
        ).data

        return Response({
            'student_id':  student.id,
            'nickname':    student.nickname,
            'school_class': {
                'id':      student.school_class.id,
                'name':    student.school_class.name,
                'subject': {
                    'id':   subject.id,
                    'name': subject.name,
                },
            },
            'units': unit_data,
        })


# ── GET /api/leaderboard/ ────────────────────────────────────────────────────

class LeaderboardView(StudentAuthMixin, APIView):
    """
    Class-scoped leaderboard — top students ranked by total XP.
    Returns nickname only; real_name is never included.
    Capped at 50 entries to keep the payload small.
    """

    def get(self, request):
        student      = request.user
        school_class = student.school_class

        rows = (
            Student.objects
            .filter(school_class=school_class)
            .annotate(
                total_xp=Coalesce(Sum('progress__total_xp'), 0),
                boss_defeats=Count('progress', filter=Q(progress__boss_defeated=True)),
            )
            .order_by('-total_xp', 'nickname')
            .values_list('id', 'nickname', 'total_xp', 'boss_defeats')
            [:50]
        )

        entries = [
            {
                'rank':         rank,
                'nickname':     nickname,
                'total_xp':     total_xp,
                'boss_defeats': boss_defeats,
                'is_me':        sid == student.id,
            }
            for rank, (sid, nickname, total_xp, boss_defeats) in enumerate(rows, start=1)
        ]

        ser = LeaderboardEntrySerializer(entries, many=True)
        return Response(ser.data)


# ── POST /api/events/ ─────────────────────────────────────────────────────────

class UsageEventCreateView(StudentAuthMixin, APIView):

    def post(self, request):
        ser = UsageEventSerializer(data=request.data)
        ser.is_valid(raise_exception=True)

        UsageEvent.objects.create(
            student          = request.user,
            event_type       = ser.validated_data['event_type'],
            device_info      = ser.validated_data['device_info'],
            duration_seconds = ser.validated_data['duration_seconds'],
        )

        return Response(status=status.HTTP_201_CREATED)
