# Generated by Django 5.1.4 on 2026-07-23 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('mcq', 'Multiple choice'), ('fill', 'Fill in the blank'), ('speak', 'Speaking'), ('write', 'Writing')], default='mcq', max_length=10)),
            ],
            options={
                'ordering': ['unit', 'title'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, default='MA', max_length=100)),
                ('paid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500)),
                ('sentence', models.CharField(blank=True, help_text='Fill-in-the-blank stem; use ___ as the placeholder.', max_length=500)),
                ('audio_prompt', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.CharField(max_length=200)),
                ('choices', models.JSONField(default=list, help_text='Ordered list of answer strings.')),
                ('choice_emojis', models.JSONField(blank=True, default=list, help_text='Optional emoji for each choice (Template A shooter cards). Same length as choices.')),
                ('tip', models.TextField(blank=True, help_text='Shown to the student after answering.')),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('template_tag', models.CharField(choices=[('shooter', 'Template A — Correct-choice shooter'), ('runner', 'Template B — Two-lane runner'), ('catch_sound', 'Template C — Catch the sound'), ('defend_line', 'Template D — Defend the line'), ('speed_quiz', 'Template E — Speed quiz')], default='speed_quiz', max_length=20)),
                ('exercise_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.exerciseset')),
            ],
            options={
                'ordering': ['exercise_set', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('join_code', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('paid_until', models.DateField(blank=True, help_text='Per-class billing override. Leave blank to inherit from School.paid_until.', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'School classes',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('real_name', models.CharField(blank=True, help_text='NEVER expose in student-facing or leaderboard API responses. Teacher/admin views only.', max_length=200)),
                ('pin', models.CharField(max_length=4)),
                ('device_token', models.UUIDField(default=uuid.uuid4, help_text='Rotated on re-authentication from a new device. Client caches locally; Student/Progress rows in Postgres are always the source of truth.', unique=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.schoolclass')),
            ],
            options={
                'ordering': ['school_class', 'nickname'],
                'unique_together': {('school_class', 'nickname')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.school')),
            ],
            options={
                'ordering': ['school', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.subject'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_free', models.BooleanField(default=False, help_text='Unit 1-style free sample: accessible without a paid_until date.')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.subject')),
                ('unlock_requires', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='core.unit')),
            ],
            options={
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audio_text', models.TextField(blank=True, help_text='What browser TTS reads aloud. Leave blank to use the body text.')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.unit')),
            ],
            options={
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='core.unit'),
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.CharField(choices=[('shooter', 'Template A — Correct-choice shooter'), ('runner', 'Template B — Two-lane runner'), ('catch_sound', 'Template C — Catch the sound'), ('defend_line', 'Template D — Defend the line'), ('speed_quiz', 'Template E — Speed quiz')], default='speed_quiz', max_length=20)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('hearts', models.PositiveSmallIntegerField(default=3)),
                ('seconds_per_question', models.PositiveSmallIntegerField(default=8)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to='core.unit')),
            ],
            options={
                'verbose_name_plural': 'Bosses',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='e.g. session_start, lesson_complete, boss_attempt, boss_win, boss_loss', max_length=50)),
                ('device_info', models.CharField(blank=True, help_text='User-agent or device class string.', max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='core.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher')], default='TEACHER', max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_defeated', models.BooleanField(default=False)),
                ('golden_boss_defeated', models.BooleanField(default=False, help_text='Awarded for beating the boss with no mistakes.')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.ManyToManyField(blank=True, related_name='completions', to='core.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.unit')),
            ],
            options={
                'verbose_name_plural': 'Progress',
                'ordering': ['student', 'unit'],
                'unique_together': {('student', 'unit')},
            },
        ),
    ]
